openapi: 3.0.0
info:
  version: 0.0.2
  title: Consumption Prediction API
  description: |-
    The Consumption Prediction API enables users to access critical consumption prediction data to be used for purposes such system planning for electricity infrastructure. The API is organized based on the REST architecture  and returns responses in JSON /xml format. 

    Users can make up to 10,000 requests a day to the API at a rate of 100 requests per second.
  termsOfService: 'https://eguide.io/#terms-of-use/'
  contact:
    name: e-GUIDE Initiative
    url: 'https://eguide.io/#contact'
    email: info@eguide.io
  license:
    name: Consumption Prediction License
    url: 'https://eguide.io/#license'
servers:
  - url: 'https://api.eguide.io/v0'
    description: eGUIDE Energy API (Beta)
paths:
  /prediction:
    get:
      tags:
        - Consumption Predictions
      description: 'Obtain consumption predictions for the specified point or polygon. '
      operationId: get-household-prediction
      parameters:
        - name: aoi
          in: query
          description: |-
            AOI String -- use POLYGON or POINT 
            --Using CRS EPSG:4326
          required: true
          schema:
            type: string
            items:
              type: number
            example: POINT(35.8843 4.0665)
        - name: resolution
          description: '{None, 250} '
          schema:
            type: integer
            example: 250
          in: query
        - name: summary_only
          description: 'If TRUE, omits cell-level data in response.'
          schema:
            type: boolean
            example: false
          in: query
        - schema:
            type: string
            example: MYAPIKEY123456
          in: header
          name: x-api-key
          required: true
      responses:
        '200':
          description: 'successful '
          content:
            application/json:
              schema:
                type: object
              examples:
                Polygon AOI summary-only:
                  value:
                    data:
                      number_of_cells: 6
                      summary_only: true
                    data_summary:
                      high_class_pooled_prob_mean: 0.58
                      high_class_pooled_prob_std_dev: 0.07
                      high_class_total_count: 20
                      low_class_pooled_prob_mean: 0.63
                      low_class_pooled_prob_std_dev: 0.09
                      low_class_total_count: 36
                      total_structure_count: 56
                    model_metadata:
                      description: Model output generated for EGUIDE API Includes 1 country Intended for production
                      model_output_id: 1
                      model_run_date: '2020-07-23'
                      model_version: 0.1.1
                      resolution (meters): 250
                    request:
                      AOI_coords: '''POLYGON((35.8843 4.0665,35.8851 4.0660, 35.8843 4.0606, 35.8795 4.0658, 35.8843 4.0665 ))'''
                      AOI_type: polygon
                      other params: {}
                      requested_resolution: '250'
                      summary_only: true
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    Code: BadRequestError
                    Message: 'BadRequestError: Shape Coordinates missing'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    message: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    Code: NotFoundError
                    Message: 'NotFoundError: No structures found for query aoi ''POINT(35.0 4.0665)'''
        '500':
          description: Internal Server Error
      summary: ''
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: Consumption Predictions
    description: Get household consumption prediction details
security:
  - apikey: []
